### PR TITLE
Make sure that no empty mails will be send anymore

### PR DESCRIPTION
**Pull request by Toon-Van-Engeland**
I do not want empty mails anymore, because this makes me sad :cry:

### CODE REVIEW

**Comment by llJochemll** [comment]
@Toon-Van-Engeland if you change the unit test for invalid input I'll merge

**Comment by Toon-Van-Engeland** [comment]
https://github.com/llJochemll/CateringNotification/pull/27#issuecomment-562962010 @llJochemll fair point, it's now done with commit d7780d30d036ccb70fdb6c69ece79c51b6c13f8a

**Comment by llJochemll** [comment]
Still 1 test that is failing: https://dev.azure.com/jochemdejaeghere/github/_build/results?buildId=242&view=ms.vss-test-web.build-test-results-tab

**Comment by Toon-Van-Engeland** [comment]
Yeah I know, the test is failing because there isn't a menu on the site at the moment and the test only works of there are menus on the site.

**Pull request merged**
